name: Main

on:
  pull_request:
    branches: [ "develop" ]

jobs:

  create-proj:
 
    runs-on: self-hosted
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make envfile
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
        echo "CACHE_REDIS=${{ secrets.CACHE_REDIS }}" >> .env

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
  
    - name: Build and run services
      run: |
        docker-compose down
        docker-compose up -d --build

    - name: Check running containers
      run: docker ps
